/**
 * Centralized Audit Action Constants
 */
module.exports = Object.freeze({
  // Inventory Item Actions
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  ARCHIVE: 'ARCHIVE',

  // Stock Movement Actions
  STOCK_IN: 'STOCK_IN',
  STOCK_OUT: 'STOCK_OUT',
  STOCK_ADJUST: 'STOCK_ADJUST',
  STOCK_MOVE: 'STOCK_MOVE',

  // Storage Location Actions
  LOCATION_CREATE: 'LOCATION_CREATE',
  LOCATION_UPDATE: 'LOCATION_UPDATE',
  LOCATION_DELETE: 'LOCATION_DELETE',

  // Project Actions
  PROJECT_CREATE: 'PROJECT_CREATE',
  PROJECT_UPDATE: 'PROJECT_UPDATE',
  PROJECT_DELETE: 'PROJECT_DELETE',

  // Buy List Actions
  BUY_LIST_ADD: 'BUY_LIST_ADD',
  BUY_LIST_UPDATE: 'BUY_LIST_UPDATE',
  BUY_LIST_DELETE: 'BUY_LIST_DELETE',

  // User & Security Actions
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DISABLE: 'USER_DISABLE',
  USER_ENABLE: 'USER_ENABLE',
  ROLE_CHANGE: 'ROLE_CHANGE',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  LOGIN: 'LOGIN',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',

  // Data Import & Export Actions
  IMPORT: 'IMPORT',
  EXPORT: 'EXPORT'
});
